/**
 * @file ConstexprProgramming.hpp
 * @brief Compile-time programming with `constexpr`, `consteval`, `constinit` and class-type NTTPs.
 *
 * Modern C++ lets ordinary-looking code run inside the compiler. This header demonstrates:
 *  - `constexpr` functions with loops, branches and local state (math, strings, sorting, searching);
 *  - `consteval` "immediate" functions that *must* be evaluated at compile time;
 *  - `std::is_constant_evaluated()` to pick a compile-time algorithm vs. a faster runtime one;
 *  - compile-time lookup tables generated by `constexpr` lambdas (`makeTable`);
 *  - literal class types (`ConstexprPlanet`, `ConstexprFleet`) whose member functions run at compile time;
 *  - class-type non-type template parameters (`FixedString`) for compile-time string tags;
 *  - transient dynamic allocation in constant expressions (`std::vector` inside `constexpr`, C++20);
 *  - variadic metaprogramming with fold expressions.
 *
 * Every result in this file is verified with `static_assert` at the bottom, so if the header compiles
 * the computations are correct. (The file was previously misspelled `ContexprProgramming.hpp`.)
 */
#pragma once

#include <array>
#include <atomic>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <iostream>
#include <limits>
#include <numbers>
#include <string_view>
#include <type_traits>
#include <vector>

namespace CppVerseHub::Modern::ConstexprProgramming {

// ===== COMPILE-TIME CONSTANTS =====

inline constexpr double PI = std::numbers::pi;                ///< pi.
inline constexpr double LIGHT_SPEED = 299792458.0;            ///< Speed of light in m/s.
inline constexpr double EARTH_MASS = 5.972e24;                ///< Earth mass in kg.
inline constexpr double EARTH_RADIUS = 6.371e6;               ///< Earth mean radius in m.
inline constexpr double SUN_MASS = 1.989e30;                  ///< Solar mass in kg.
inline constexpr double ASTRONOMICAL_UNIT = 1.496e11;         ///< Earth-Sun distance in m.
inline constexpr double GRAVITATIONAL_CONSTANT = 6.67430e-11; ///< G in m^3 kg^-1 s^-2.

// ===== COMPILE-TIME MATH =====

/// @brief Absolute value usable in constant expressions.
/// @param x Input. @return |x|.
[[nodiscard]] constexpr double absValue(double x) noexcept {
    return x < 0.0 ? -x : x;
}

/// @brief Integer power by repeated squaring (O(log n) multiplications); negative exponents invert.
/// @param base Base. @param exponent Integer exponent.
/// @return base^exponent.
[[nodiscard]] constexpr double power(double base, int exponent) noexcept {
    if (exponent < 0) {
        return 1.0 / power(base, -exponent);
    }
    double result = 1.0;
    while (exponent > 0) {
        if ((exponent & 1) != 0) {
            result *= base;
        }
        base *= base;
        exponent >>= 1;
    }
    return result;
}

/// @brief n! as a 64-bit integer (valid for n <= 20; larger n saturates to the max value).
/// @param n Non-negative input. @return n!.
[[nodiscard]] constexpr std::uint64_t factorial(unsigned n) noexcept {
    if (n > 20U) {
        return std::numeric_limits<std::uint64_t>::max();
    }
    std::uint64_t result = 1;
    for (unsigned i = 2; i <= n; ++i) {
        result *= i;
    }
    return result;
}

/// @brief Square root by Newton-Raphson iteration until convergence; returns NaN for negatives.
/// @param x Input. @return sqrt(x).
[[nodiscard]] constexpr double sqrtNewton(double x) noexcept {
    if (x < 0.0) {
        return std::numeric_limits<double>::quiet_NaN();
    }
    if (x == 0.0 || x == std::numeric_limits<double>::infinity()) {
        return x;
    }
    double guess = x < 1.0 ? 1.0 : x;
    for (int i = 0; i < 200; ++i) {
        const double next = 0.5 * (guess + x / guess);
        if (next == guess) {
            break;
        }
        // Newton for sqrt converges monotonically from above; stop once it stops decreasing.
        if (next > guess) {
            break;
        }
        guess = next;
    }
    return guess;
}

/// @brief Square root that uses the constexpr algorithm during constant evaluation and `std::sqrt`
///        at run time (`std::sqrt` is not constexpr before C++26).
/// @param x Input. @return sqrt(x).
[[nodiscard]] constexpr double adaptiveSqrt(double x) noexcept {
    if (std::is_constant_evaluated()) {
        return sqrtNewton(x);
    }
    return std::sqrt(x);
}

/// @brief Sine via range reduction to [-pi, pi] and a Taylor series (accurate to ~1e-12).
/// @param x Angle in radians. @return sin(x).
[[nodiscard]] constexpr double sinTaylor(double x) noexcept {
    const double twoPi = 2.0 * PI;
    const auto turns = static_cast<long long>(x / twoPi);
    x -= static_cast<double>(turns) * twoPi;
    if (x > PI) {
        x -= twoPi;
    } else if (x < -PI) {
        x += twoPi;
    }
    double term = x;
    double sum = x;
    for (int n = 1; n < 20; ++n) {
        term *= -x * x / static_cast<double>((2 * n) * (2 * n + 1));
        sum += term;
    }
    return sum;
}

/// @brief Greatest common divisor (Euclid); result is non-negative.
/// @param a First value. @param b Second value. @return gcd(a, b).
[[nodiscard]] constexpr std::int64_t gcd(std::int64_t a, std::int64_t b) noexcept {
    a = a < 0 ? -a : a;
    b = b < 0 ? -b : b;
    while (b != 0) {
        const std::int64_t t = a % b;
        a = b;
        b = t;
    }
    return a;
}

/// @brief Least common multiple, computed as a / gcd * b to avoid intermediate overflow.
/// @param a First value. @param b Second value. @return lcm(a, b) (0 if either is 0).
[[nodiscard]] constexpr std::int64_t lcm(std::int64_t a, std::int64_t b) noexcept {
    if (a == 0 || b == 0) {
        return 0;
    }
    const std::int64_t r = (a / gcd(a, b)) * b;
    return r < 0 ? -r : r;
}

/// @brief Primality test by trial division.
/// @param n Candidate. @return True if n is prime.
[[nodiscard]] constexpr bool isPrime(std::uint64_t n) noexcept {
    if (n < 2) {
        return false;
    }
    if (n % 2 == 0) {
        return n == 2;
    }
    for (std::uint64_t d = 3; d * d <= n; d += 2) {
        if (n % d == 0) {
            return false;
        }
    }
    return true;
}

// ===== consteval: immediate functions =====

/// @brief Factorial that can only be evaluated at compile time (calling it with a runtime value is
///        ill-formed). Useful for constants that must never cost runtime.
/// @param n Input (n <= 20). @return n!.
[[nodiscard]] consteval std::uint64_t compileTimeFactorial(unsigned n) {
    return factorial(n);
}

/// @brief n-th Fibonacci number, compile time only.
/// @param n Index (F(0)=0, F(1)=1). @return F(n).
[[nodiscard]] consteval std::uint64_t compileTimeFibonacci(unsigned n) {
    std::uint64_t a = 0;
    std::uint64_t b = 1;
    for (unsigned i = 0; i < n; ++i) {
        const std::uint64_t t = a + b;
        a = b;
        b = t;
    }
    return a;
}

// ===== SPACE PHYSICS =====

/// @brief Circular orbital velocity v = sqrt(GM/r).
/// @param mass Central mass (kg). @param radius Orbit radius (m). @return Velocity in m/s.
[[nodiscard]] constexpr double orbitalVelocity(double mass, double radius) noexcept {
    return adaptiveSqrt(GRAVITATIONAL_CONSTANT * mass / radius);
}

/// @brief Escape velocity v = sqrt(2GM/r).
/// @param mass Body mass (kg). @param radius Body radius (m). @return Velocity in m/s.
[[nodiscard]] constexpr double escapeVelocity(double mass, double radius) noexcept {
    return adaptiveSqrt(2.0 * GRAVITATIONAL_CONSTANT * mass / radius);
}

/// @brief Orbital period T = 2*pi*sqrt(a^3 / GM) (Kepler's third law).
/// @param semiMajorAxis Semi-major axis (m). @param centralMass Central mass (kg). @return Period in s.
[[nodiscard]] constexpr double orbitalPeriod(double semiMajorAxis, double centralMass) noexcept {
    return 2.0 * PI * adaptiveSqrt(power(semiMajorAxis, 3) / (GRAVITATIONAL_CONSTANT * centralMass));
}

/// @brief Euclidean distance between two 3D points.
/// @return Distance.
[[nodiscard]] constexpr double distance3d(double x1, double y1, double z1, double x2, double y2,
                                          double z2) noexcept {
    const double dx = x2 - x1;
    const double dy = y2 - y1;
    const double dz = z2 - z1;
    return adaptiveSqrt(dx * dx + dy * dy + dz * dz);
}

/// @brief Sphere volume 4/3 pi r^3. @param radius Radius. @return Volume.
[[nodiscard]] constexpr double sphereVolume(double radius) noexcept {
    return (4.0 / 3.0) * PI * power(radius, 3);
}

/// @brief Sphere surface area 4 pi r^2. @param radius Radius. @return Area.
[[nodiscard]] constexpr double sphereSurfaceArea(double radius) noexcept {
    return 4.0 * PI * radius * radius;
}

// ===== COMPILE-TIME STRINGS =====

/// @brief ASCII upper-casing. @param c Character. @return Upper-case character.
[[nodiscard]] constexpr char toUpper(char c) noexcept {
    return (c >= 'a' && c <= 'z') ? static_cast<char>(c - 'a' + 'A') : c;
}

/// @brief ASCII digit test. @param c Character. @return True for '0'..'9'.
[[nodiscard]] constexpr bool isDigit(char c) noexcept {
    return c >= '0' && c <= '9';
}

/// @brief ASCII letter test. @param c Character. @return True for a-z / A-Z.
[[nodiscard]] constexpr bool isAlpha(char c) noexcept {
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
}

/// @brief Counts occurrences of a character. @param s Text. @param c Character. @return Count.
[[nodiscard]] constexpr std::size_t countChar(std::string_view s, char c) noexcept {
    std::size_t n = 0;
    for (char ch : s) {
        n += (ch == c) ? 1U : 0U;
    }
    return n;
}

/// @brief 32-bit FNV-1a hash. @param s Text. @return Hash value.
[[nodiscard]] constexpr std::uint32_t fnv1a(std::string_view s) noexcept {
    std::uint32_t hash = 2166136261U;
    for (char c : s) {
        hash ^= static_cast<std::uint8_t>(c);
        hash *= 16777619U;
    }
    return hash;
}

/// @brief Caesar shift of a single letter; non-letters are unchanged, negative shifts are supported.
/// @param c Character. @param shift Shift amount (any integer). @return Shifted character.
[[nodiscard]] constexpr char caesarEncode(char c, int shift) noexcept {
    const int s = ((shift % 26) + 26) % 26;
    if (c >= 'a' && c <= 'z') {
        return static_cast<char>('a' + (c - 'a' + s) % 26);
    }
    if (c >= 'A' && c <= 'Z') {
        return static_cast<char>('A' + (c - 'A' + s) % 26);
    }
    return c;
}

/// @brief Inverse of `caesarEncode`. @param c Character. @param shift Shift used to encode. @return Original.
[[nodiscard]] constexpr char caesarDecode(char c, int shift) noexcept {
    return caesarEncode(c, -shift);
}

/// @brief Applies `caesarEncode` to a fixed-size string literal at compile time.
/// @param text Null-terminated literal. @param shift Shift. @return Encoded copy (still null-terminated).
template <std::size_t N>
[[nodiscard]] constexpr std::array<char, N> caesarEncodeString(const char (&text)[N], int shift) noexcept {
    std::array<char, N> out{};
    for (std::size_t i = 0; i < N; ++i) {
        out[i] = caesarEncode(text[i], shift);
    }
    return out;
}

/// @brief A string literal usable as a class-type non-type template parameter (C++20).
/// @tparam N Size of the literal including the terminating null.
template <std::size_t N>
struct FixedString {
    std::array<char, N> chars{}; ///< Characters including the null terminator.

    /// @brief Captures a string literal. @param text The literal.
    constexpr FixedString(const char (&text)[N]) noexcept { // NOLINT(google-explicit-constructor)
        for (std::size_t i = 0; i < N; ++i) {
            chars[i] = text[i];
        }
    }
    /// @brief View of the characters without the null terminator. @return string_view.
    [[nodiscard]] constexpr std::string_view view() const noexcept { return {chars.data(), N - 1}; }
    /// @brief Length excluding the null terminator. @return Length.
    [[nodiscard]] static constexpr std::size_t size() noexcept { return N - 1; }
};

/// @brief A compile-time tag type identified by a string; its hash is a compile-time constant.
/// @tparam Name The tag name.
template <FixedString Name>
struct NamedTag {
    static constexpr std::string_view name = Name.view();   ///< The tag name.
    static constexpr std::uint32_t id = fnv1a(Name.view()); ///< Hash of the name.
};

// ===== COMPILE-TIME ARRAYS =====

/// @brief Sum of a std::array. @param arr Input. @return Sum.
template <typename T, std::size_t N>
[[nodiscard]] constexpr T arraySum(const std::array<T, N>& arr) noexcept {
    T sum{};
    for (const T& v : arr) {
        sum += v;
    }
    return sum;
}

/// @brief Maximum element of a non-empty std::array. @param arr Input. @return Max element.
template <typename T, std::size_t N>
    requires(N > 0)
[[nodiscard]] constexpr T arrayMax(const std::array<T, N>& arr) noexcept {
    T best = arr[0];
    for (std::size_t i = 1; i < N; ++i) {
        if (best < arr[i]) {
            best = arr[i];
        }
    }
    return best;
}

/// @brief Minimum element of a non-empty std::array. @param arr Input. @return Min element.
template <typename T, std::size_t N>
    requires(N > 0)
[[nodiscard]] constexpr T arrayMin(const std::array<T, N>& arr) noexcept {
    T best = arr[0];
    for (std::size_t i = 1; i < N; ++i) {
        if (arr[i] < best) {
            best = arr[i];
        }
    }
    return best;
}

/// @brief Returns a sorted copy (insertion sort: simple, stable and constexpr-friendly).
/// @param arr Input by value. @return Sorted array.
template <typename T, std::size_t N>
[[nodiscard]] constexpr std::array<T, N> sortedCopy(std::array<T, N> arr) noexcept {
    for (std::size_t i = 1; i < N; ++i) {
        T key = arr[i];
        std::size_t j = i;
        while (j > 0 && key < arr[j - 1]) {
            arr[j] = arr[j - 1];
            --j;
        }
        arr[j] = key;
    }
    return arr;
}

/// @brief Binary search in a sorted std::array.
/// @param arr Sorted input. @param value Value to find. @return Index of `value`, or N if absent.
template <typename T, std::size_t N>
[[nodiscard]] constexpr std::size_t binarySearch(const std::array<T, N>& arr, const T& value) noexcept {
    std::size_t lo = 0;
    std::size_t hi = N;
    while (lo < hi) {
        const std::size_t mid = lo + (hi - lo) / 2;
        if (arr[mid] < value) {
            lo = mid + 1;
        } else if (value < arr[mid]) {
            hi = mid;
        } else {
            return mid;
        }
    }
    return N;
}

/// @brief Generates a lookup table by calling `f(i)` for i in [0, N) at compile time.
/// @param f Generator taking a `std::size_t`. @return The table.
template <std::size_t N, typename F>
[[nodiscard]] constexpr auto makeTable(F f) {
    std::array<std::invoke_result_t<F, std::size_t>, N> table{};
    for (std::size_t i = 0; i < N; ++i) {
        table[i] = f(i);
    }
    return table;
}

/// @brief First N Fibonacci numbers starting 0, 1, 1, 2, ...
/// @return Array of Fibonacci numbers.
template <std::size_t N>
[[nodiscard]] constexpr std::array<std::uint64_t, N> generateFibonacci() noexcept {
    std::array<std::uint64_t, N> fib{};
    for (std::size_t i = 0; i < N; ++i) {
        fib[i] = (i < 2) ? i : fib[i - 1] + fib[i - 2];
    }
    return fib;
}

/// @brief First N prime numbers.
/// @return Array of primes in increasing order.
template <std::size_t N>
[[nodiscard]] constexpr std::array<std::uint64_t, N> generatePrimes() noexcept {
    std::array<std::uint64_t, N> primes{};
    std::size_t count = 0;
    for (std::uint64_t candidate = 2; count < N; ++candidate) {
        if (isPrime(candidate)) {
            primes[count++] = candidate;
        }
    }
    return primes;
}

/// @brief Sum of squares 1..n computed through a transient `std::vector` (C++20 constexpr allocation).
///        Falls back to a loop when the standard library lacks constexpr vector.
/// @param n Upper bound. @return Sum of i^2 for i in [1, n].
[[nodiscard]] constexpr std::int64_t sumOfSquaresViaVector(int n) {
#if defined(__cpp_lib_constexpr_vector) && __cpp_lib_constexpr_vector >= 201907L
    std::vector<std::int64_t> squares;
    for (int i = 1; i <= n; ++i) {
        squares.push_back(static_cast<std::int64_t>(i) * i);
    }
    std::int64_t sum = 0;
    for (std::int64_t s : squares) {
        sum += s;
    }
    return sum; // the vector's storage is released before the constant evaluation ends
#else
    std::int64_t sum = 0;
    for (int i = 1; i <= n; ++i) {
        sum += static_cast<std::int64_t>(i) * i;
    }
    return sum;
#endif
}

// ===== LITERAL TYPES FOR THE SPACE GAME =====

/// @brief Planet classification.
enum class PlanetType : int { Terrestrial = 1, GasGiant = 2, IceGiant = 3, DwarfPlanet = 4 };

/// @brief Fleet mission kind.
enum class MissionType : int { Exploration = 1, Combat = 2, Colonization = 3, Trade = 4, Rescue = 5 };

/// @brief A literal-type planet whose derived quantities can be computed at compile time.
struct ConstexprPlanet {
    int id = 0;                                ///< Identifier.
    PlanetType type = PlanetType::Terrestrial; ///< Classification.
    double mass = 0.0;                         ///< Mass in kg.
    double radius = 1.0;                       ///< Radius in m.
    bool habitable = false;                    ///< Supports life.

    /// @brief Surface gravity g = GM/r^2. @return m/s^2.
    [[nodiscard]] constexpr double surfaceGravity() const noexcept {
        return GRAVITATIONAL_CONSTANT * mass / (radius * radius);
    }
    /// @brief Escape velocity. @return m/s.
    [[nodiscard]] constexpr double escapeVelocity() const noexcept {
        return ConstexprProgramming::escapeVelocity(mass, radius);
    }
    /// @brief Surface area. @return m^2.
    [[nodiscard]] constexpr double surfaceArea() const noexcept { return sphereSurfaceArea(radius); }
    /// @brief Volume. @return m^3.
    [[nodiscard]] constexpr double volume() const noexcept { return sphereVolume(radius); }
    /// @brief Mean density. @return kg/m^3.
    [[nodiscard]] constexpr double density() const noexcept { return mass / volume(); }
};

/// @brief A literal-type fleet.
struct ConstexprFleet {
    int id = 0;                                     ///< Identifier.
    int shipCount = 0;                              ///< Number of ships.
    double fuelPercentage = 0.0;                    ///< Fuel level 0..100.
    MissionType mission = MissionType::Exploration; ///< Current mission.

    /// @brief Heuristic combat power. @return ships * fuel fraction * 10.
    [[nodiscard]] constexpr double combatPower() const noexcept {
        return static_cast<double>(shipCount) * (fuelPercentage / 100.0) * 10.0;
    }
    /// @brief Operational if it has ships and more than 20% fuel. @return Operational flag.
    [[nodiscard]] constexpr bool isOperational() const noexcept {
        return fuelPercentage > 20.0 && shipCount > 0;
    }
    /// @brief Heuristic range. @return fuel * ships * 0.5.
    [[nodiscard]] constexpr double maxRange() const noexcept {
        return fuelPercentage * static_cast<double>(shipCount) * 0.5;
    }
};

/// @brief The eight planets of the solar system as a compile-time table.
inline constexpr std::array<ConstexprPlanet, 8> SOLAR_SYSTEM{{
    {1, PlanetType::Terrestrial, 3.301e23, 2.4397e6, false}, // Mercury
    {2, PlanetType::Terrestrial, 4.867e24, 6.0518e6, false}, // Venus
    {3, PlanetType::Terrestrial, 5.972e24, 6.371e6, true},   // Earth
    {4, PlanetType::Terrestrial, 6.417e23, 3.3896e6, false}, // Mars
    {5, PlanetType::GasGiant, 1.898e27, 6.9911e7, false},    // Jupiter
    {6, PlanetType::GasGiant, 5.683e26, 5.8232e7, false},    // Saturn
    {7, PlanetType::IceGiant, 8.681e25, 2.5362e7, false},    // Uranus
    {8, PlanetType::IceGiant, 1.024e26, 2.4622e7, false},    // Neptune
}};

/// @brief Counts habitable planets. @param planets Input. @return Count.
template <std::size_t N>
[[nodiscard]] constexpr int countHabitable(const std::array<ConstexprPlanet, N>& planets) noexcept {
    int count = 0;
    for (const auto& p : planets) {
        count += p.habitable ? 1 : 0;
    }
    return count;
}

/// @brief Counts planets of a given type. @param planets Input. @param type Type. @return Count.
template <std::size_t N>
[[nodiscard]] constexpr int countOfType(const std::array<ConstexprPlanet, N>& planets,
                                        PlanetType type) noexcept {
    int count = 0;
    for (const auto& p : planets) {
        count += (p.type == type) ? 1 : 0;
    }
    return count;
}

/// @brief Total mass. @param planets Input. @return Sum of masses.
template <std::size_t N>
[[nodiscard]] constexpr double totalMass(const std::array<ConstexprPlanet, N>& planets) noexcept {
    double total = 0.0;
    for (const auto& p : planets) {
        total += p.mass;
    }
    return total;
}

/// @brief A fleet configuration is valid when every fleet is operational, there are at least
///        `minShips` ships and the mean fuel is at least `minMeanFuel`.
/// @param fleets Fleets to check. @param minShips Ship threshold. @param minMeanFuel Fuel threshold.
/// @return Whether the configuration is valid.
template <std::size_t N>
[[nodiscard]] constexpr bool validateFleetConfiguration(const std::array<ConstexprFleet, N>& fleets,
                                                        int minShips = 10,
                                                        double minMeanFuel = 50.0) noexcept {
    if constexpr (N == 0) {
        return false;
    } else {
        int ships = 0;
        double fuel = 0.0;
        for (const auto& f : fleets) {
            if (!f.isOperational()) {
                return false;
            }
            ships += f.shipCount;
            fuel += f.fuelPercentage;
        }
        return ships >= minShips && fuel / static_cast<double>(N) >= minMeanFuel;
    }
}

// ===== VARIADIC METAPROGRAMMING =====

/// @brief Number of types in a pack. @return sizeof...(Ts).
template <typename... Ts>
[[nodiscard]] constexpr std::size_t countTypes() noexcept {
    return sizeof...(Ts);
}

/// @brief Whether `T` occurs in the pack. @return True if found.
template <typename T, typename... Ts>
[[nodiscard]] constexpr bool containsType() noexcept {
    return (std::is_same_v<T, Ts> || ...);
}

/// @brief Index of the first occurrence of `T` in the pack, or sizeof...(Ts) if absent.
/// @return Index.
template <typename T, typename... Ts>
[[nodiscard]] constexpr std::size_t indexOfType() noexcept {
    constexpr std::array<bool, sizeof...(Ts) + 1> matches{std::is_same_v<T, Ts>..., true};
    std::size_t i = 0;
    while (!matches[i]) {
        ++i;
    }
    return i;
}

/// @brief Sum of a value pack (0 for empty). @return Sum.
template <auto... Values>
[[nodiscard]] constexpr auto sumValues() noexcept {
    return (Values + ... + 0);
}

/// @brief Product of a value pack (1 for empty). @return Product.
template <auto... Values>
[[nodiscard]] constexpr auto multiplyValues() noexcept {
    return (Values * ... * 1);
}

// ===== COMPILE-TIME TABLES =====

inline constexpr auto FIBONACCI_SEQUENCE = generateFibonacci<20>(); ///< F(0)..F(19).
inline constexpr auto FIRST_PRIMES = generatePrimes<10>();          ///< First 10 primes.
inline constexpr auto SQUARES_TABLE = makeTable<16>(
    [](std::size_t i) { return static_cast<int>(i * i); }); ///< i^2 for i < 16.
inline constexpr auto SINE_TABLE = makeTable<9>(
    [](std::size_t i) { return sinTaylor(static_cast<double>(i) * PI / 8.0); });          ///< sin(k*pi/8).
inline constexpr double EARTH_ESCAPE_VELOCITY = escapeVelocity(EARTH_MASS, EARTH_RADIUS); ///< ~11186 m/s.
inline constexpr double EARTH_ORBITAL_VELOCITY = orbitalVelocity(SUN_MASS,
                                                                 ASTRONOMICAL_UNIT); ///< ~29780 m/s.
inline constexpr std::uint32_t GAME_NAME_HASH = fnv1a("CppVerseHub"); ///< FNV-1a of the project name.

// ===== COMPILE-TIME VERIFICATION =====

/// @brief Tolerance comparison for static_asserts. @return |a-b| <= eps * max(1, |b|).
[[nodiscard]] constexpr bool approxEqual(double a, double b, double eps = 1e-9) noexcept {
    const double scale = absValue(b) > 1.0 ? absValue(b) : 1.0;
    return absValue(a - b) <= eps * scale;
}

static_assert(power(2.0, 10) == 1024.0 && power(2.0, -2) == 0.25 && power(5.0, 0) == 1.0);
static_assert(factorial(0) == 1 && factorial(10) == 3628800 && factorial(20) == 2432902008176640000ULL);
static_assert(compileTimeFactorial(12) == 479001600);
static_assert(compileTimeFibonacci(0) == 0 && compileTimeFibonacci(10) == 55 &&
              compileTimeFibonacci(50) == 12586269025ULL);
static_assert(approxEqual(sqrtNewton(2.0), std::numbers::sqrt2) && sqrtNewton(81.0) == 9.0 &&
              sqrtNewton(0.0) == 0.0);
static_assert(approxEqual(sqrtNewton(0.25), 0.5));
static_assert(approxEqual(sinTaylor(PI / 2.0), 1.0) && approxEqual(sinTaylor(0.0), 0.0));
static_assert(approxEqual(sinTaylor(7.0 * PI / 2.0), -1.0, 1e-8));
static_assert(gcd(48, 18) == 6 && gcd(-48, 18) == 6 && lcm(4, 6) == 12 && lcm(0, 5) == 0);
static_assert(lcm(3037000499LL, 3037000493LL) > 0); // no overflow in a / gcd * b
static_assert(isPrime(2) && isPrime(97) && !isPrime(1) && !isPrime(91));
static_assert(toUpper('q') == 'Q' && toUpper('7') == '7' && isDigit('5') && !isAlpha('5'));
static_assert(countChar("CppVerseHub", 'p') == 2);
static_assert(fnv1a("") == 2166136261U && fnv1a("a") == 0xE40C292CU);
static_assert(caesarEncode('x', 3) == 'a' && caesarDecode('a', 3) == 'x' && caesarEncode('B', -1) == 'A');
static_assert(caesarEncodeString("Hal", 1)[0] == 'I' && caesarEncodeString("Hal", 1)[2] == 'm');
static_assert(NamedTag<"Fleet">::name == "Fleet" && NamedTag<"Fleet">::id == fnv1a("Fleet"));
static_assert(NamedTag<"Fleet">::id != NamedTag<"Planet">::id);
static_assert(arraySum(std::array{1, 2, 3, 4}) == 10 && arrayMax(std::array{3, 9, 2}) == 9);
static_assert(arrayMin(std::array{3, 9, 2}) == 2);
static_assert(sortedCopy(std::array{64, 25, 12, 22, 11}) == std::array{11, 12, 22, 25, 64});
static_assert(binarySearch(std::array{1, 3, 5, 7}, 5) == 2 && binarySearch(std::array{1, 3, 5, 7}, 4) == 4);
static_assert(FIBONACCI_SEQUENCE[0] == 0 && FIBONACCI_SEQUENCE[19] == 4181);
static_assert(FIRST_PRIMES == std::array<std::uint64_t, 10>{2, 3, 5, 7, 11, 13, 17, 19, 23, 29});
static_assert(SQUARES_TABLE[15] == 225 && approxEqual(SINE_TABLE[4], 1.0));
static_assert(sumOfSquaresViaVector(10) == 385);
static_assert(EARTH_ESCAPE_VELOCITY > 11180.0 && EARTH_ESCAPE_VELOCITY < 11190.0);
static_assert(EARTH_ORBITAL_VELOCITY > 29700.0 && EARTH_ORBITAL_VELOCITY < 29900.0);
static_assert(orbitalPeriod(ASTRONOMICAL_UNIT, SUN_MASS) / 86400.0 > 365.0 &&
              orbitalPeriod(ASTRONOMICAL_UNIT, SUN_MASS) / 86400.0 < 366.0);
static_assert(SOLAR_SYSTEM[2].surfaceGravity() > 9.8 && SOLAR_SYSTEM[2].surfaceGravity() < 9.85);
static_assert(SOLAR_SYSTEM[2].density() > 5500.0 && SOLAR_SYSTEM[2].density() < 5530.0);
static_assert(countHabitable(SOLAR_SYSTEM) == 1 && countOfType(SOLAR_SYSTEM, PlanetType::GasGiant) == 2);
static_assert(totalMass(SOLAR_SYSTEM) > 2.6e27 && totalMass(SOLAR_SYSTEM) < 2.7e27);
static_assert(validateFleetConfiguration(std::array{ConstexprFleet{1, 15, 85.5, MissionType::Exploration},
                                                    ConstexprFleet{2, 12, 92.0, MissionType::Combat}}));
static_assert(!validateFleetConfiguration(std::array{ConstexprFleet{1, 15, 10.0, MissionType::Trade}}));
static_assert(ConstexprFleet{1, 10, 50.0, MissionType::Combat}.combatPower() == 50.0);
static_assert(countTypes<int, double, char>() == 3 && containsType<int, double, int>() &&
              !containsType<float, double, int>());
static_assert(indexOfType<char, int, double, char>() == 2 && indexOfType<float, int>() == 1);
static_assert(sumValues<1, 2, 3, 4, 5>() == 15 && multiplyValues<2, 3, 4>() == 24 && sumValues<>() == 0);
static_assert(distance3d(0, 0, 0, 3, 4, 12) == 13.0);

/// @brief Prints the compile-time results (they were all computed by the compiler).
/// @param out Destination stream.
inline void demonstrateConstexpr(std::ostream& out = std::cout) {
    // constinit: guaranteed static initialisation (no static-init-order fiasco), yet mutable.
    constinit static std::atomic<int> invocations{0};
    ++invocations;

    out << "\n=== Compile-time Programming (constexpr / consteval / constinit) ===\n";
    out << "Earth escape velocity:  " << EARTH_ESCAPE_VELOCITY << " m/s\n";
    out << "Earth orbital velocity: " << EARTH_ORBITAL_VELOCITY << " m/s\n";
    constexpr double yearDays = orbitalPeriod(ASTRONOMICAL_UNIT, SUN_MASS) / 86400.0;
    out << "Kepler period at 1 AU:  " << yearDays << " days\n";
    out << "consteval 12! = " << compileTimeFactorial(12) << ", F(50) = " << compileTimeFibonacci(50) << '\n';

    out << "Fibonacci table:";
    for (auto v : FIBONACCI_SEQUENCE) {
        out << ' ' << v;
    }
    out << "\nPrime table:";
    for (auto p : FIRST_PRIMES) {
        out << ' ' << p;
    }
    out << "\nsin(k*pi/8) table:";
    for (double s : SINE_TABLE) {
        out << ' ' << s;
    }
    out << '\n';

    constexpr auto sorted = sortedCopy(std::array{42, 17, 89, 3, 56, 23, 91, 12});
    out << "sortedCopy:";
    for (int v : sorted) {
        out << ' ' << v;
    }
    out << " | min=" << arrayMin(sorted) << " max=" << arrayMax(sorted) << " sum=" << arraySum(sorted)
        << " index(56)=" << binarySearch(sorted, 56) << '\n';

    constexpr auto secret = caesarEncodeString("CppVerseHub", 3);
    out << "Caesar(+3) of CppVerseHub: " << secret.data() << ", FNV-1a hash: " << GAME_NAME_HASH << '\n';
    out << "NamedTag<\"Fleet\">: name=" << NamedTag<"Fleet">::name << " id=" << NamedTag<"Fleet">::id << '\n';
    out << "sumOfSquaresViaVector(10) (constexpr std::vector) = " << sumOfSquaresViaVector(10) << '\n';

    const auto& earth = SOLAR_SYSTEM[2];
    const auto& jupiter = SOLAR_SYSTEM[4];
    out << "Earth:   g=" << earth.surfaceGravity() << " m/s^2, density=" << earth.density() << " kg/m^3\n";
    out << "Jupiter: g=" << jupiter.surfaceGravity() << " m/s^2, v_esc=" << jupiter.escapeVelocity()
        << " m/s\n";
    out << "Habitable planets: " << countHabitable(SOLAR_SYSTEM)
        << ", gas giants: " << countOfType(SOLAR_SYSTEM, PlanetType::GasGiant) << '\n';
    out << "Metaprogramming: countTypes<int,double,float,char>=" << countTypes<int, double, float, char>()
        << " indexOfType<char,...>=" << indexOfType<char, int, double, char>()
        << " sumValues<1..5>=" << sumValues<1, 2, 3, 4, 5>() << '\n';
    out << "adaptiveSqrt(2) at run time uses std::sqrt: " << adaptiveSqrt(2.0) << '\n';
    out << "demonstrateConstexpr invocations (constinit counter): " << invocations.load() << '\n';
}

} // namespace CppVerseHub::Modern::ConstexprProgramming
